name: CI
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node: ['18.x']

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Use Node ${{ matrix.node }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}

            - name: Install dependencies and build (with cache)
              uses: bahmutov/npm-install@v1

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Lint
              run: yarn lint

            - name: Build
              run: yarn build
